# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'dotenv'
gem "influxdb", "~> 0.7.0"
gem "sinatra", "~> 2.2"
gem "sinatra-contrib", "~> 2.2"
